### PR TITLE
Adapt Pelorus charts to deploy in Openshift 4.9+ clusters

### PR DESCRIPTION
**Pull request by flacatus**
## Describe the behavior changes introduced in this PR
The current PR tries to deploy pelorus on Openshift 4.9 with the following changes:
- Change subscriptions of grafana to v4 channel and update the grafana versions
- Increase Prometheus version to not use v1alpha CRDS(not compatible with 4.8 or less openshift versions)
- Remove the spec.name value from grafana CR specs, due it is not compatible with latest grafana operators
- 
## Linked Issues?

related to #321  

## Testing Instructions

Please include any additional commands or pointers in addition to our [standard PR testing process](/docs/Development.md#testing-pull-requests).

@redhat-cop/mdt

### CODE REVIEW

**Comment by weshayutin** [comment]
nice.. will give this a go :)

**Review by mpryc — APPROVED** [review]
Tested on the following versions:
OCP 4.9.9
OCP 4.8.2

Helm install/uninstall works great.

As in the offline discussion with the author of this PR it will cause pelorus incompatible with EOL version of OCP (4.6). The following change is incompatible:
```
apiVersion: batch/v1
kind: CronJob
```

**Comment by mpryc** [comment]
@flacatus one more version bump in the file:
 charts/operators/Chart.yaml
 
 I think you can sync it with pelorus as we will have it in the next release tag.
@KevinMGranger do you agree?

**Comment by weshayutin** [comment]
on 4.7 grafana is hitting an issue.

grafana-operator-controller-manager:
(combined from similar events): Error: container create failed: time="2022-02-28T20:32:00Z" level=error msg="container_linux.go:366: starting container process caused: chdir to cwd (\"/home/nonroot\") set in config.json failed: permission denied"

**Comment by weshayutin** [comment]
> 

FYI... my cluster was at 4.7.0, I'm updating the cluster to 4.7.43 and will retry :)

**Comment by mpryc** [comment]
> > 
> 
> FYI... my cluster was at 4.7.0, I'm updating the cluster to 4.7.43 and will retry :)

I can confirm this issue on 4.7.0.

Sounds like similar issue to https://bugzilla.redhat.com/show_bug.cgi?id=1934177

**Comment by mpryc** [comment]
@weshayutin @flacatus The grafana oerator is failing on 4.7.0, but I believe it's a mentioned problem with runc. Here is really nice post about the overall issue: https://danielmangum.com/posts/runc-chdir-to-cwd/

Anyway I have tested this on 4.7.14 and 4.8.12 as well on the 4.9.9 and everything works ok. So I am pretty confident this is the right approach and for the releases 4.7.0 the path is to update OCP as it's not the issue with pelorus itself.

**Review by mpryc — APPROVED** [review]

**Pull request merged**
