### PR TITLE
Webhook exporter

### PR DESCRIPTION
**Pull request by shaheinm**
Supersedes #250

### CODE REVIEW

**Comment by haithamshahin333** [comment]
@shaheinm @etsauer as discussed, a good improvement on this feature would be to refactor it such that there is the concept of a committime "provider" (i.e. currently we can gather committime data either from openshift builds or from the webhook exporter). This could be added as a config defined by the user and then rather than having a separate genericexporter, the committime exporter has logic to evaluate that config and select the right provider accordingly.

**Comment by springdo** [comment]
Bump .... Any word on when this is going to move forward?

**Comment by ckavili** [comment]
hey everyone! I just tried this to run the exporter with the following values:

```
...
  - app_name: committime-generic
    env_from_secrets:
    - mongodb-build-webhook
    - gitlab-secret
    source_context_dir: exporters/
    extraEnv:
    - name: APP_FILE
      value: committime/app.py
    - name: LOG_LEVEL
      value: DEBUG
    - name: PROVIDER
      value: "webhook"
    source_ref: webhook-exporter
    source_url: https://github.com/shaheinm/pelorus.git
```
  
 and got this error:

```
raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff5f595cac0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

I'm not sure but it seems this is related with Kubernetes v12 package https://github.com/kubernetes-client/python/issues/1284

```
$ oc debug dc/committime-generic
(app-root) sh-4.4$ pip list | grep kubernetes
kubernetes          12.0.1   
```

there is a suggested fix https://github.com/kubernetes-client/python/issues/1284#issuecomment-750737547 or version 11.0 can be used as in the deploytime-exporter 🙂

```
$ oc rsh deploytime-exporter-1-vbvtl 
(app-root) sh-4.4$ pip list | grep kubernetes
kubernetes          11.0.0 
```

**Comment by itewk** [comment]
this still planned to be implmeneted?

**Comment by mpryc** [comment]
I am closing this PR as a result of current cleanup of open issues/PRs.

The webhook exporter may be still valid use case, however implementation will be very different as there was a lot of changes in the exporter code. Closing this PR in favor of the new one, which will be proposed in the near future.

**Pull request closed without merging**
