### PR TITLE
Easy release process

### PR DESCRIPTION
**Pull request by mpryc**
Using script to calculate release versions and wrapping it around Makefile.

Developer has option to create major/minor/patch releases by simply
invoking make major-release / make minor-release / make release
commands and creating PR from changed by this process files.

@redhat-cop/mdt

### CODE REVIEW

**Comment by mpryc** [comment]
@weshayutin New documentation can be viewed directly on the: https://pelorus--401.org.readthedocs.build/en/401/Development/#release-management-process

**Review by weshayutin — APPROVED** [review]
worked for me :) https://termbin.com/eth0

**Pull request merged**
