### PR TITLE
Pelorus Operator

### PR DESCRIPTION
**Pull request by mpryc**
Generated pelorus operator based on Helm Charts

## Testing Instructions
```
make dev-env
source .venv/bin/activate

# To create fresh or re-generate operator:
rm -rf pelorus-operator
mkdir pelorus-operator
./scripts/create_pelorus_operator

# To build and push operator files, login to quay, e.g.
podman login -u="migtools+pelorus" -p="{SECRET_HASH}" quay.io

# To build operator and bundle and push it to quay:
make podman-build
make podman-push
make bundle-build
make bundle-push

# To install bundle in the cluster from previously pushed to registry bundle
export KUBECONFIG=<path_to_kubeconfig>
export NAMESPACE=pelorus
oc create ns "${NAMESPACE}"
operator-sdk run bundle quay.io/migtools/pelorus-operator-bundle:v0.0.1 --namespace "${NAMESPACE}"
```

@redhat-cop/mdt

### CODE REVIEW

**Comment by weshayutin** [comment]
0/ 
I'm getting an image pull backoff
Back-off pulling image "quay.io/migtools/pelorus-operator:0.0.41"

  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  71s   deployment-controller  Scaled up replica set pelorus-operator-controller-manager-5b4b587b8f to 1
(.venv) [whayutin@thinkdoe pelorus-operator]$ oc logs deployment.apps/pelorus-operator-controller-manager
Error from server (BadRequest): container "manager" in pod "pelorus-operator-controller-manager-5b4b587b8f-8vq45" is waiting to start: trying and failing to pull image

**Comment by KevinMGranger** [comment]
Is that because the version was incremented, but no image was published for it?

**Comment by mpryc** [comment]
@weshayutin @KevinMGranger This is ready to be reviewed and merged if you are happy.

There are two minor issues, which I would like to address later, because this will just be addressing those smaller ones:
 - pelorus-operator-controller-manager-* pod is going into CrashLoopBackOff, however pelorus is deployed correctly. I suspect there may be a problem with proper resources to that pod ?
 - There is `Hook post-install pelorus/templates/grafana-post-install-hook.yaml` hook which should be reworked as manager is complaining that `serviceaccounts "grafana-api" already exists`

**Comment by weshayutin** [comment]
```
(.venv) [whayutin@thinkdoe scripts]$ operator-sdk run bundle quay.io/migtools/pelorus-operator-bundle:v0.0.1 --namespace "${NAMESPACE}"
INFO[0004] Creating a File-Based Catalog of the bundle "quay.io/migtools/pelorus-operator-bundle:v0.0.1" 
INFO[0005] Generated a valid File-Based Catalog         
INFO[0013] Created registry pod: quay-io-migtools-pelorus-operator-bundle-v0-0-1 
INFO[0013] Created CatalogSource: pelorus-operator-catalog 
INFO[0013] OperatorGroup "operator-sdk-og" created      
INFO[0013] Created Subscription: pelorus-operator-v0-0-55-sub 
INFO[0019] Approved InstallPlan install-2n5pn for the Subscription: pelorus-operator-v0-0-55-sub 
INFO[0019] Waiting for ClusterServiceVersion "pelorus/pelorus-operator.v0.0.55" to reach 'Succeeded' phase 
INFO[0019]   Waiting for ClusterServiceVersion "pelorus/pelorus-operator.v0.0.55" to appear 
INFO[0046]   Found ClusterServiceVersion "pelorus/pelorus-operator.v0.0.55" phase: Pending 
INFO[0047]   Found ClusterServiceVersion "pelorus/pelorus-operator.v0.0.55" phase: InstallReady 
INFO[0048]   Found ClusterServiceVersion "pelorus/pelorus-operator.v0.0.55" phase: Installing 
FATA[0120] Failed to run bundle: error waiting for CSV to install: timed out waiting for the condition 
(.venv) [whayutin@thinkdoe scripts]$ 

lastUpdateTime: '2022-11-28T21:34:32Z'
  message: >-
    installing: waiting for deployment pelorus-operator-controller-manager to
    become ready: deployment "pelorus-operator-controller-manager" not
    available: Deployment does not have minimum availability.
  phase: Installing
  reason: InstallWaiting

```

This is a step, but should not yet be considered working.

**Review by weshayutin — APPROVED** [review]

**Pull request merged**
