### PR TITLE
fix: mockoon script failing silently

### PR DESCRIPTION
**Pull request by mateusoliveira43**
Signed-off-by: Mateus Oliveira <msouzaol@redhat.com>

## Describe the behavior changes introduced in this PR

Remove the behavior of silently fail from the mockoon script.

## Linked Issues

No.

## Testing Instructions

Check CI logs for the mockoon job and run `make mockoon-tests` locally.

### CODE REVIEW

**Comment by mpryc** [comment]
@mateusoliveira43 what is the delete_me.txt file for?

**Comment by mateusoliveira43** [comment]
> @mateusoliveira43 what is the delete_me.txt file for?

Just to trigger the CI heheheeh I was planning to ask Kevin to delete it in his PR, but now thinking, I believe is better to change the job yaml file to also trigger when there is changes to the mockoon script. What you think?

**Comment by mateusoliveira43** [comment]
@KevinMGranger can you check if this ok so we can review your mockoon PR?

**Comment by mpryc** [comment]
This works, however there is small issue which can be addressed in separate PR.

Running the `make mockoon-tests` without prior running `make dev-env` will cause the mockoon tests to fail.

**Pull request merged**
