### PR TITLE
Use quay.io images in the deployment of pelorus exporters

### LINKED ISSUE #373: Use quay.io images in the deployment of pelorus exporters
Rather then build pelorus exporter images from scratch each time deployment happens we should use published and properly tagged images from quay.io.

Depends-On: PR #358.

### PR DESCRIPTION
**Pull request by mpryc**
Fixes #373 , which by default uses "stable" images from quay.io to deploy exporter images.

The below options are per exporter instance, so each exporter may be deployed with different tag/image or method.

User have option to still use git based deployment when:
```
  source_url OR source_ref is specified
```

User also have option to provide image tag different then stable by:
```
  image_tag: <tag name>
```

Or fully qualified image url with or without image_tag, examples:
```
  image_name: quay.io/pelorus/committime-exporter
  image_name: quay.io/pelorus/committime-exporter:latest
```

There are also some pre-conditions to ensure user specified proper values, e.g. using GIT and image deployment at the same time or specifying image tag when the image tag is already part of image_name.

Matrix of possible errors and results:
https://hackmd.io/@openshift-mig-eng/rkNC3W8dq

Depends on #483

@redhat-cop/mdt

### CODE REVIEW

**Comment by mpryc** [comment]
Converted to draft as I need to fix issue where image presented with the tag is properly handled:

Example:
```
    image_name: "quay.io/migi/committime-exporter:mytag"
```

Above requires currently specifying:
```
image_tag: mytag
```

**Comment by weshayutin** [comment]
testing this now

**Comment by mpryc** [comment]
@weshayutin

As listed in the matrix table, there are many options which are in contradiction to each other and should not be mixed:

https://hackmd.io/@openshift-mig-eng/rkNC3W8dq#Possible-solutions

Testing instructions:

1. Create values.yaml with instances configured in a way described below
2. Make sure config maps are installed in the cluster `oc apply -f path/to/configmaps/directory`
3. Deploy Pelorus as usual `helm install --debug pelorus charts/pelorus --namespace pelorus  --values path/to/values.yaml`
4. Check if pods are running `oc get pods -n pelorus`

To test *just* quay installation create instance and ensure no   source_url OR source_ref is specified, make sure exporter_type is specified, example

```
exporters:
  instances:
  - app_name: deploytime-exporter
    exporter_type: deploytime
    env_from_configmaps:
    - pelorus-config
    - deploytime-config
```

To make sure GIT deployment is still possible, create instance with either source_url or source_ref, example:

```
exporters:
  instances:
  - app_name: deploytime-exporter
    exporter_type: deploytime
    source_ref: master
    env_from_configmaps:
    - pelorus-config
    - deploytime-config
```

That is it.

You can have full matrix of different methods in one deployment, here is example of exporters part for the values.yaml config:

```
exporters:
  instances:
  - app_name: deploytime-exporter-minimal-config
    exporter_type: deploytime
    env_from_configmaps:
    - pelorus-config
    - deploytime-config

  - app_name: deploytime-exporter-custom-image
    exporter_type: deploytime
    image_name: "quay.io/migi/committime-exporter:stable"
    env_from_configmaps:
    - pelorus-config
    - deploytime-config
    
  - app_name: deploytime-exporter-custom-image-custom-imagetag
    exporter_type: deploytime
    image_name: "quay.io/migi/committime-exporter"
    image_tag: latest
    env_from_configmaps:
    - pelorus-config
    - deploytime-config
    
  - app_name: deploytime-exporter-custom-imagetag
    exporter_type: deploytime
    image_tag: latest
    env_from_configmaps:
    - pelorus-config
    - deploytime-config

  - app_name: deploytime-exporter-custom-image-with-tag
    exporter_type: deploytime
    image_name: "quay.io/migi/committime-exporter:latest"
    env_from_configmaps:
    - pelorus-config
    - deploytime-config

  - app_name: deploytime-exporter-git-source-ref
    exporter_type: deploytime
    source_ref: master
    env_from_configmaps:
    - pelorus-config
    - deploytime-config

  - app_name: deploytime-exporter-git-source-ref-custom-url
    exporter_type: deploytime
    source_ref: master
    source_url: https://github.com/mpryc/pelorus.git
    env_from_configmaps:
    - pelorus-config
    - deploytime-config

  - app_name: deploytime-exporter-git-custom-url
    exporter_type: deploytime
    source_url: https://github.com/konveyor/pelorus.git
    env_from_configmaps:
    - pelorus-config
    - deploytime-config
```

**Comment by weshayutin** [comment]
commit 9a9539d0e0123204767332850398c0fa7231f611 (HEAD -> quay_image)
```
oc apply -f charts/pelorus/configmaps/
configmap/committime-config configured
configmap/deploytime-config unchanged
configmap/failuretime-config configured
configmap/pelorus-config unchanged
```
```
[whayutin@thinkdoe QUAY]$ cat quay.yaml 
# Default values for deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# to reset password: htpasswd -s -b -n internal changeme
openshift_prometheus_htpasswd_auth: internal:{SHA}+pvrmeQCmtWmYVOZ57uuITVghrM=
openshift_prometheus_basic_auth_pass: changeme
extra_prometheus_hosts:

# Uncomment this if your cluster serves privately signed certificates
# custom_ca: true

deployment:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: pelorus
    app.kubernetes.io/version: v0.33.0
exporters:
  instances:
  - app_name: deploytime-exporter
    exporter_type: deploytime
    env_from_configmaps:
    - pelorus-config
    - deploytime-config
#  - app_name: committime-exporter
#    exporter_type: committime
#    env_from_configmaps:
#    - pelorus-config
#    - committime-config
```

bah.. execution is here: https://termbin.com/nvng

Doesn't seem to install the deploytime exporter for me.

**Comment by mpryc** [comment]
@weshayutin I see what's happening. I have hoped we would release 1.6.0 that would create "stable" branch, however this did not happen yet, so we don't have proper image tag in quay. To fix this we either wait for 1.6.0 to be created or you can add this to your config:

```
    image_tag: latest
```

So your instance config looks like:

```
exporters:
  instances:
  - app_name: deploytime-exporter
    exporter_type: deploytime
    image_tag: latest
    env_from_configmaps:
    - pelorus-config
    - deploytime-config
```
It's chicken-egg issue, but once we have first 'stable' tag on an image, things should work out of the box with such minimal config that defaults to 'stable' tag.

**Pull request merged**
