### PR TITLE
update Tekton demo with optional build types

### LINKED ISSUE #478: Research generic commit time to raise the level of certainty to ditch tekton specific support

### LINKED ISSUE #526: Make python tekton demo in demo/ attach committime annotations
1. This helps serve as an example for the "generic commit time" workflow (the one created in #498)
2. This will help us validate that it's an adequate way to support tekton (for #478)
3. It also serves as a tekton workflow itself, like a more specific example for number 1.

### PR DESCRIPTION
**Pull request by weshayutin**
## Linked Issues?

resolves #526 
resolves #478 

related to #<issue number> <-- Use this if it shouldn't

## Testing Instructions

check out pull request
./demo-tekton <git_url>

### CODE REVIEW

**Comment by weshayutin** [comment]
@mpryc @KevinMGranger this is ready :)

**Comment by mpryc** [comment]
1. In the Tekton UI I am getting (while running binary or buildconfig builds):

```
Pipeline basic-python-tekton/basic-python-tekton-pipeline can't be Run; it contains Tasks that don't exist: Couldn't retrieve Task "debug": tasks.tekton.dev "debug" not found
```

That's after switching to: `apiVersion: tekton.dev/v1alpha1`

2. While running binary build the branch on the repo side is "tekton_buildConfig", thinking laud here if it should be per type of the build, so maybe "tekton_binary" or even to be more explicity "tekton_pelorus_binary", "tekton_pelorus_buildConfig", "tekton_pelorus_s2i".

**Comment by weshayutin** [comment]
@mpryc @KevinMGranger ok... sorry the updated code needs to be in the remote branch.  Some changes were required.
to test:   ./demo-tekton.sh -r refs/pull/587/head

**Pull request merged**
