### PR TITLE
Modified resources for the pelorus-operator

### PR DESCRIPTION
**Pull request by mpryc**
Pelorus operator v0.0.3 with updated resources for the pelorus operator manager pod.

1. Ensure no other pelorus-operator is installed
2. Run bundle with this PR: ``` operator-sdk run bundle quay.io/migtools/pelorus-operator-bundle:v0.0.3 --namespace pelorus ```

Signed-off-by: Michal Pryc <mpryc@redhat.com>

Please include any additional commands or pointers in addition to our [standard PR testing process](/docs/Development.md#testing-pull-requests).

@redhat-cop/mdt

### CODE REVIEW

**Comment by mpryc** [comment]
The memory usage in this PR was set based on the pod memory usage metric from the cluster (attached).
Screenshot from 2022-12-06 13-59-33

**Comment by mpryc** [comment]
Fixes #731

**Comment by mpryc** [comment]
Screenshot from 2022-12-07 12-05-58

**Review by weshayutin — APPROVED** [review]

**Comment by weshayutin** [comment]
Deployed two exporters by creating an instance of pelorus post operator install w/ the following config.
```
spec:
  exporters:
    global: {}
    instances:
      - app_name: deploytime-exporter
        exporter_type: deploytime
        extraEnv:
          - name: LOG_LEVEL
            value: DEBUG
          - name: NAMESPACES
            value: 'mongo-persistent,demoapp1,demoapp2,demoapp3'
      - app_name: committime-exporter
        exporter_type: committime
        extraEnv:
          - name: LOG_LEVEL
            value: DEBUG
          - name: NAMESPACES
            value: 'mongo-persistent,demoapp1,demoapp2,demoapp3'
```

Click Save...

The operator spun up the commit time exporter, and deploytime exporter pod and they are running.

```
(.venv) [whayutin@thinkdoe pelorus]$ oc get all -n pelorus | grep time
pod/committime-exporter-1-deploy                                      0/1     Completed   0               3m55s
pod/committime-exporter-1-ncmgc                                       1/1     Running     0               3m52s
pod/deploytime-exporter-1-bsjr4                                       1/1     Running     0               3m52s
pod/deploytime-exporter-1-deploy                                      0/1     Completed   0               3m55s
replicationcontroller/committime-exporter-1   1         1         1       3m55s
replicationcontroller/deploytime-exporter-1   1         1         1       3m55s
service/committime-exporter                                   ClusterIP   172.30.19.85     <none>        8080/TCP            3m56s
service/deploytime-exporter                                   ClusterIP   172.30.14.45     <none>        8080/TCP            3m56s
deploymentconfig.apps.openshift.io/committime-exporter   1          1         1         config,image(committime-exporter:stable)
deploymentconfig.apps.openshift.io/deploytime-exporter   1          1         1         config,image(deploytime-exporter:stable)
imagestream.image.openshift.io/committime-exporter   image-registry.openshift-image-registry.svc:5000/pelorus/committime-exporter   stable   3 minutes ago
imagestream.image.openshift.io/deploytime-exporter   image-registry.openshift-image-registry.svc:5000/pelorus/deploytime-exporter   stable   3 minutes ago
route.route.openshift.io/committime-exporter   committime-exporter-pelorus.apps.cluster-wdh11092022b.wdh11092022b.mg.dog8code.com          committime-exporter   http                                 None
route.route.openshift.io/deploytime-exporter   deploytime-exporter-pelorus.apps.cluster-wdh11092022b.wdh11092022b.mg.dog8code.com          deploytime-exporter   http                                 None

```

Deploytime has metrics \0/
```
# TYPE deploy_timestamp gauge
deploy_timestamp{app="todolist",image_sha="sha256:04559c4ebdde446ade9a67cd58124fdcb9e28f2ffc7fac923e0f3845c9f3d54a",namespace="mongo-persistent"} 1.668809883e+09 1668809883000
# HELP deployment_active Active deployments in cluster
# TYPE deployment_active gauge
deployment_active{app="todolist",image_sha="sha256:04559c4ebdde446ade9a67cd58124fdcb9e28f2ffc7fac923e0f3845c9f3d54a",namespace="mongo-persistent"} 1.668809883e+09
```

**Comment by weshayutin** [comment]
Screenshot from 2022-12-07 14-57-11

**Pull request merged**
