### PR TITLE
Deprecate Grafana snapshot job

### PR DESCRIPTION
**Pull request by mpryc**
Grafana snapshot job was aimed to give access to the metrics without login to the grafana dashboard.

This feature isn't working as expected and currently can be deprecated.

If needed we should consider:
 1. Creating anonymous access to the grafana instance
 2. Rework current logic to create such snapshots

Signed-off-by: Michal Pryc <mpryc@redhat.com>

@redhat-cop/mdt

### CODE REVIEW

**Comment by mpryc** [comment]
Fixes #732

**Comment by mpryc** [comment]
@KevinMGranger can we merge this without conftest? I have disabled already those, however they are in the list of checks as disable happened after it failed?

**Review by weshayutin — APPROVED** [review]

**Pull request merged**
