### PR TITLE
include failure exporter check in e2e

### PR DESCRIPTION
**Pull request by weshayutin**
* two switches here
  * intent to test failure exporter
  * GITHUB_SECRET or in future JIRA_SECRET
    * either or both can be used
* invoked w/
./scripts/run-pelorus-e2e-tests -o konveyor -e failure

* once 4.10 passes w/ updates, this call will change in the
makefile

## Linked Issues?
https://github.com/openshift/release/pull/29693
resolves #<issue number> <-- Use this if merging should auto-close an issue

related to #<issue number> <-- Use this if it shouldn't

## Testing Instructions

Please include any additional commands or pointers in addition to our [standard PR testing process](/docs/Development.md#testing-pull-requests).

@redhat-cop/mdt

### CODE REVIEW

**Comment by mpryc** [comment]
/hold

Something went wrong while testing script on a local box (attached output from run)
[e2e.txt](https://github.com/konveyor/pelorus/files/8953069/e2e.txt)

**Comment by weshayutin** [comment]
> /hold
> 
> Something went wrong while testing script on a local box (attached output from run) [e2e.txt](https://github.com/konveyor/pelorus/files/8953069/e2e.txt)

@mpryc looks like mongo didn't pull or start. I've seen that happen once before.  That is all in the mongo-persistent.yaml template not 100% what to do about that tbh

**Comment by weshayutin** [comment]
test all

**Comment by weshayutin** [comment]
seems good to me.
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/konveyor_pelorus/512/pull-ci-konveyor-pelorus-master-4.8-e2e-openshift/1539348168125190144/artifacts/e2e-openshift/e2e/build-log.txt

**Pull request merged**
