### PR TITLE
Use API_USER instead of USER

### LINKED ISSUE #553: committime: GIT_USER should override USER when both are set
While `$USER` is cleaner for running exporters in a container, where the user running it doesn't matter, it makes for hard-to-spot errors in local testing. Setting `$GIT_USER` does nothing!

(This would be easier to spot with #554.)

In `upgrade_legacy_vars`, instead of
```python
git_user = utils.get_env_var("GIT_USER")
if not utils.get_env_var("USER"):
    os.environ["USER"] = git_user
```
we should have:
```python
git_user = utils.get_env_var("GIT_USER")
user = utils.get_env_var("USER")
os.environ["USER"] = git_user or user
```

### PR DESCRIPTION
**Pull request by KevinMGranger**
resolves #553

### CODE REVIEW

**Comment by weshayutin** [comment]
I'm finding instances of just "USER" across some of the various docs.
labs/consultant/03-Exporters.md
mocks/README.md
samples/todolist_commit_deploy.md

AFAICT the intention is to globally replace s/USER/API_USER is that correct or no?

**Comment by KevinMGranger** [comment]
Ah, thought I caught them all.

We typically don't manually squash, no? We have github do it for us?

**Comment by mpryc** [comment]
@KevinMGranger one last nit:

docs/Development.md

```
diff --git a/docs/Development.md b/docs/Development.md
index 94b1526..7badb06 100644
--- a/docs/Development.md
+++ b/docs/Development.md
@@ -188,7 +188,7 @@ Code also comes with a nice debugger feature. Here is a starter configuration to
             "program": "${workspaceFolder}/exporters/committime/app.py",
             "console": "integratedTerminal",
             "env": {
-                "GITHUB_USER": "<github username here>",
+                "API_USER": "<github username here>",
                 "GITHUB_TOKEN": "<personal access token here>",
                 "LOG_LEVEL": "INFO",
                 "APP_LABEL": "app.kubernetes.io/name"

```

**Pull request merged**
