### PR TITLE
Build image per pelorus exporter

### PR DESCRIPTION
**Pull request by mpryc**
Fix for issue #358.

Currently pelorus builds exporters as one, meaning each exporter is exactly the same,
just the name of the image differs.

This improves how we are building and publishing images to image registry,
ensuring each exporter contains only requires set of python files.

Futher work will involve ensuring we are installing only those
requirements that are needed per exporter.

Symbolic links in each exporter are created to ensure backwards compability
with the current helm charts and it's data from values.yaml.

Github action to build image was updated to use v2 version of s2i image and
some variables were introduced to easy testing in a separate quay.io namespace.

## Linked Issues?

resolves #<issue number> <-- Use this if merging should auto-close an issue

related to #<issue number> <-- Use this if it shouldn't

## Testing Instructions

Please include any additional commands or pointers in addition to our [standard PR testing process](/docs/Development.md#testing-pull-requests).

@redhat-cop/mdt

### CODE REVIEW

**Comment by etsauer** [comment]
@mpryc I wouldn't worry about introducing non-backwards compatible changes. We don't allow/support/recommend/document intermixing older/newer versions of the exporters together so compatibility-wise it won't be an issue.

**Comment by KevinMGranger** [comment]
A couple thoughts:

- Is this still a WIP? If so, we should mark it as a draft.
- We said we wanted to use the makefiles as the standard way of setting up the environment-- do we want the github actions to use `make`? Then we're not updating things in multiple spots each time.
- Is there a reason to have the additional layer of `pelorus_common`? Can we put `requirements.txt` and `setup.*` in `exporters/pelorus`?
    - Or maybe symlink to `pelorus` instead of `pelorus_common`?
- Will a symlink out of the context dir work in the first place? If we want to make the image only include what's necessary, then we still need to keep the other directories when we do this. Maybe we should delete the other directories at build time?

**Comment by mpryc** [comment]
@KevinMGranger 

> * Is this still a WIP? If so, we should mark it as a draft.
I had this as draft when was testing locally, but now it's not. We need to make decision if this is the right approach or drop it.

> * We said we wanted to use the makefiles as the standard way of setting up the environment-- do we want the github actions to use `make`? Then we're not updating things in multiple spots each time.
Definitely, but not as part of this review. Filled issue #374 for that. 

> * Is there a reason to have the additional layer of `pelorus_common`? Can we put `requirements.txt` and `setup.*` in `exporters/pelorus`?
I remember why I did that. In short isort was unhappy with the order in which the imports were pulled and there was difference on the local venv system versus github actions. I fixed it in the last commit by adding .isort.cfg and explicitly stating pelorus is known_first_party package. Note that this caused isort to reorder a bit the imports in various files. But now both venv and github is giving same results.

>   * Or maybe symlink to `pelorus` instead of `pelorus_common`?
Yes I like symlink better. 
In the latest revision of this PR I have removed requirements.txt from pelorus_common all together. Each exporter is using pelorus_common not as real python library but more of a folder with just one common python script and then it should list it's dependencies in the requirements.txt  

> * Will a symlink out of the context dir work in the first place? If we want to make the image only include what's necessary, then we still need to keep the other directories when we do this. Maybe we should delete the other directories at build time?

Not really. Source 2 image makes it easier as symlink is being created on the resulting image as a standard folder with content in it (content from what was in the symlink).

I have updated latest revision as there was also file conflict from your last merge.

**Comment by mpryc** [comment]
I am closing this PR. Currently we are building images, not fully optimized, however if needed this will be implemented different way. Current codebase have lot's of newer changes and many of the conflicting files, so it's easier to create fresh change, but it's not priority atm.

**Pull request closed without merging**
