### PR TITLE
Mutually dependent auth params, switch comittime to pelorus.config

### LINKED ISSUE #578: API_USER and TOKEN should _both_ be present or _both_ be absent.
> Bitbucket requires *both* API_USER and TOKEN to be set. If API_USER or TOKEN is set and second is unset, then it will fall back to anonymous authentication without giving error:

```
401 Client Error: Unauthorized for url: https://bitbucket.org/api/2.0/repositories/michalpryc/pelorus-bitbucket/commit/e2c4ef00468dfc10aad1bd2d4c9d470160a7f471
```

> I think we should check if both are set or both are unset, otherwise users will silently use non-authorized API calls even if they requested authorized ones.

_Originally posted by @mpryc in https://github.com/konveyor/pelorus/issues/465#issuecomment-1191336433_

### PR DESCRIPTION
**Pull request by KevinMGranger**
## Describe the behavior changes introduced in this PR

Require username and token to both be set if either is set. Otherwise will log a warning and unset both.

Cleans up committime to use the new `pelorus.config` system.

Makes collectors properly inherit from `Collector`.

## Linked Issues?

resolves #578

## Testing Instructions

Please include any additional commands or pointers in addition to our [standard PR testing process](/docs/Development.md#testing-pull-requests).

@redhat-cop/mdt

### CODE REVIEW

**Comment by weshayutin** [comment]
reviewing this now

**Comment by weshayutin** [comment]
Everything worked for me on the happy path.

Set the git_provider to foo, go the expected results.
```
ValueError: ("'git_provider' must be in {'bitbucket', 'gitlab', 'azure-devops', 'github', 'gitea'} (got 'foo')", Attribute(name='git_provider', default='github', validator=<in_ validator with options {'bitbucket', 'gitlab', 'azure-devops', 'github', 'gitea'}>, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class 'str'>, converter=None, kw_only=True, inherited=False, on_setattr=None), {'bitbucket', 'gitlab', 'azure-devops', 'github', 'gitea'}, 'foo')
```
RE: the bug,
w/ just TOKEN
08-04-2022 11:17:51 INFO     Loading CommittimeConfig, inputs below:
08-04-2022 11:17:51 INFO     username='', default value; none of API_USER, GITHUB_USER, GIT_USER were set
08-04-2022 11:17:51 INFO     token=REDACTED, from env var TOKEN
08-04-2022 11:17:51 INFO     namespaces='mongo-persistent', from env var NAMESPACES
08-04-2022 11:17:51 INFO     git_api='', default value; none of GIT_API, GITHUB_API were set
08-04-2022 11:17:51 INFO     git_provider='bitbucket', from env var GIT_PROVIDER
08-04-2022 11:17:51 INFO     tls_verify=True, default value; TLS_VERIFY was not set
08-04-2022 11:17:51 WARNING  No API_USER and no TOKEN given. This is okay for public repositories only.
08-04-2022 11:17:51 INFO     =====Using BitBucket Collector=====

w/ both API_USER && TOKEN
08-04-2022 11:19:23 INFO     Loading CommittimeConfig, inputs below:
08-04-2022 11:19:23 INFO     username='weshayutin', from env var API_USER
08-04-2022 11:19:23 INFO     token=REDACTED, from env var TOKEN
08-04-2022 11:19:23 INFO     namespaces='mongo-persistent', from env var NAMESPACES
08-04-2022 11:19:23 INFO     git_api='', default value; none of GIT_API, GITHUB_API were set
08-04-2022 11:19:23 INFO     git_provider='bitbucket', from env var GIT_PROVIDER
08-04-2022 11:19:23 INFO     tls_verify=True, default value; TLS_VERIFY was not set
08-04-2022 11:19:23 INFO     =====Using BitBucket Collector=====
08-04-2022 11:19:23 INFO     Watching namespaces: {'mongo-persistent'}

nice work!

**Comment by mpryc** [comment]
awesome work !

```
Running committime exporter. No version information found.
Initializing Logger with LogLevel: DEBUG
08-05-2022 09:57:24 ERROR    load cache error: ResourceList.__init__() got an unexpected keyword argument 'base_resource_lookup'
08-05-2022 09:57:24 INFO     Loading CommittimeConfig, inputs below:
08-05-2022 09:57:24 INFO     username='testuser', from env var API_USER
08-05-2022 09:57:24 INFO     token=REDACTED, from env var TOKEN
08-05-2022 09:57:24 INFO     namespaces='bitbucket-binary', from env var NAMESPACES
08-05-2022 09:57:24 INFO     git_api='', default value; none of GIT_API, GITHUB_API were set
08-05-2022 09:57:24 INFO     git_provider='bitbucket', from env var GIT_PROVIDER
08-05-2022 09:57:24 INFO     tls_verify=True, default value; TLS_VERIFY was not set
08-05-2022 09:57:24 INFO     =====Using BitBucket Collector=====
```

**Pull request merged**
