### PR TITLE
fix: Charts links

### PR DESCRIPTION
**Pull request by mateusoliveira43**
Signed-off-by: Mateus Oliveira <msouzaol@redhat.com>

## Describe the behavior changes introduced in this PR

Fix broken links. I used `grep -Iinr 'https://pelorus.readthedocs.io' .` to help me.

## Linked Issues

resolves https://github.com/konveyor/pelorus/issues/801

## Testing Instructions

Check if the links are correct now.

### CODE REVIEW

**Comment by mateusoliveira43** [comment]
@mpryc I received this error
```
Linting charts...
Directory "charts/configmaps" is not a valid chart directory. Skipping...
Directory "charts/configmaps" is not a valid chart directory. Skipping...
Directory "charts/configmaps" is not a valid chart directory. Skipping...
Directory "charts/configmaps" is not a valid chart directory. Skipping...
Directory "charts/secrets" is not a valid chart directory. Skipping...
Directory "charts/secrets" is not a valid chart directory. Skipping...

------------------------------------------------------------------------------------------------------------------------
 Charts to be processed:
------------------------------------------------------------------------------------------------------------------------
 pelorus => (version: "2.0.4", path: "charts/pelorus")
------------------------------------------------------------------------------------------------------------------------

Saving 1 charts
Deleting outdated charts
walk.go:74: found symbolic link in path: /home/mateusoliveira43/PROJECTS/mateus_pelorus/charts/pelorus/charts resolves to /home/mateusoliveira43/PROJECTS/mateus_pelorus/charts/pelorus/subcharts. Contents of linked file included and used
walk.go:74: found symbolic link in path: /home/mateusoliveira43/PROJECTS/mateus_pelorus/charts/pelorus/charts resolves to /home/mateusoliveira43/PROJECTS/mateus_pelorus/charts/pelorus/subcharts. Contents of linked file included and used
Linting chart "pelorus => (version: \"2.0.4\", path: \"charts/pelorus\")"
Checking chart "pelorus => (version: \"2.0.4\", path: \"charts/pelorus\")" for a version bump...
Old chart version: 2.0.4
New chart version: 2.0.4
------------------------------------------------------------------------------------------------------------------------
 ✖︎ pelorus => (version: "2.0.4", path: "charts/pelorus") > chart version not ok. Needs a version bump! 
------------------------------------------------------------------------------------------------------------------------
Error: failed linting charts: failed processing charts
failed linting charts: failed processing charts
make: *** [Makefile:240: chart-lint] Error 1
Makefile:258: 🐚 ⏭ Shellcheck not found, skipping
make: Target 'lint' not remade because of errors.


Linting failed. Check the above output for hints.
```
what should I do to fix it?

**Comment by mpryc** [comment]
The links should not be updated here. They should be updated in the `scripts/pelorus-operator-patches/` and new pelorus-operator folder should be generated using our `scripts/create_pelorus_operator`.

Will create update to our dev docs to describe process.

**Review by mpryc — APPROVED** [review]

**Comment by mpryc** [comment]
The chart version needs to be bumped for the CI to pass.

**Comment by mpryc** [comment]
needs bumping versions in the `charts/pelorus/Chart.yaml`

**Review by mpryc — DISMISSED** [review]

**Review by mpryc — APPROVED** [review]

**Pull request merged**
